### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by Ellipse0934** [Ellipse0934/GSoC_assignment#1]
- [ ] Add a build system system using GNU make or Cmake.
- [ ] Upload the `atomicMin()` version of the scan along with benchmarks. (Bench code was a hack so rewrite it although the method and result was fine). Using `atomicMin` to write to a global memory the error index in the event of an error was measurably faster in the event of no error but was 5x slowed when every single index generated an error. It also avoided the large `cudaMemcpy` call and an 8 byte transfer could tell if an error was there and at what index.
- [ ] Compare against cuDPP and other standard bleeding edge libraries solutions.
- [ ] Run the HIP implementation on a similarly priced AMD card and compare the result.
- [ ] Try it on Julia and Numba CUDA respectively.
